# Generated by Django 2.1.7 on 2019-03-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hacker',
            name='transaction_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hacker',
            name='transaction_status',
            field=models.CharField(default='Não pago', max_length=100),
        ),
    ]
