# Generated by Django 2.1.7 on 2019-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0002_auto_20190320_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='transaction_code',
            field=models.CharField(blank=True, default='', max_length=39),
        ),
    ]
