# Generated by Django 2.1.7 on 2019-03-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0003_auto_20190320_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='payed',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='hacker',
            name='transaction_status',
        ),
    ]
