version: '3.7'
services:
  proxy:
    command: --docker \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG-localhost} \
      --accessLog \
      --web
  backend:
    command: python manage.py runserver 0.0.0.0:8000
