version: '3.7'
services:
  backend:
    networks:
      - default
      - proxy
  grafana:
    networks:
      - default
      - proxy
  portainer:
    networks:
      - default
      - proxy
  proxy:
    networks:
      - default
      - proxy
  celeryworker:
    networks:
      - default
  celerybeat:
    networks:
      - default
  db:
    networks:
      - default
  redis:
    networks:
      - default
  redis-exporter:
    networks:
      - default
  exporter:
    networks:
      - default
  prometheus:
    networks:
      - default

networks:
  default:
    external: false
  proxy:
    external: true
