services:
  backend:
    command:
    - daphne
    - project.asgi:application
    - --port
    - '8000'
    - --bind
    - 0.0.0.0
    - -v2
    depends_on:
    - db
    - redis
    deploy:
      labels:
        traefik.backend: api
        traefik.enable: "true"
        traefik.frontend.rule: api.localhost
        traefik.port: '8000'
        traefik.tags: localhost
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      APP_ENV: prod
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DEBUG: "False"
      DJANGO_SETTINGS_MODULE: project.settings
      NODE_ENV: production
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pass
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REDIS_URL: redis://redis:6379/0
      SERVER_HOST: http://localhost
      SERVER_NAME: localhost
      SUPERUSER_EMAIL: gustavomaronato@gmail.com
      SUPERUSER_NAME: admin
      SUPERUSER_PASSWORD: password
    image: maronato/event-manager-backend:prod
    networks:
      default:
        aliases:
        - localhost
    ports:
    - published: 8000
      target: 8000
  celerybeat:
    command: celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
    - backend
    - db
    - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      APP_ENV: prod
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DEBUG: "False"
      DJANGO_SETTINGS_MODULE: project.settings
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pass
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REDIS_URL: redis://redis:6379/0
      SERVER_HOST: http://localhost
      SUPERUSER_EMAIL: gustavomaronato@gmail.com
      SUPERUSER_NAME: admin
      SUPERUSER_PASSWORD: password
    image: maronato/event-manager-worker:prod
  celeryworker:
    command: celery -A project worker -l info
    depends_on:
    - backend
    - db
    - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      APP_ENV: prod
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DEBUG: "False"
      DJANGO_SETTINGS_MODULE: project.settings
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pass
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      REDIS_URL: redis://redis:6379/0
      SERVER_HOST: http://localhost
      SUPERUSER_EMAIL: gustavomaronato@gmail.com
      SUPERUSER_NAME: admin
      SUPERUSER_PASSWORD: password
    image: maronato/event-manager-worker:prod
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pass
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
    image: postgres:alpine
    volumes:
    - app-db-data:/var/lib/postgresql/data/pgdata:rw
  exporter:
    depends_on:
    - prometheus
    deploy:
      labels:
        traefik.backend: prometheus-exporter
        traefik.enable: "true"
        traefik.port: '9100'
        traefik.tags: localhost
    image: prom/node-exporter:latest
    ports:
    - target: 9100
  grafana:
    depends_on:
    - prometheus
    deploy:
      labels:
        traefik.backend: grafana
        traefik.enable: "true"
        traefik.frontend.rule: Host:grafana.localhost
        traefik.port: '2000'
        traefik.tags: localhost
    environment:
      GF_SECURITY_ADMIN_PASSWORD: pass
    image: grafana/grafana
    ports:
    - published: 2000
      target: 3000
    volumes:
    - grafana_data:/var/lib/grafana:rw
  portainer:
    image: portainer/portainer
    ports:
    - published: 9000
      target: 9000
    volumes:
    - portainer_data:/data:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
  prometheus:
    deploy:
      labels:
        traefik.backend: prometheus
        traefik.enable: "true"
        traefik.frontend.rule: Host:prom.localhost
        traefik.port: '9090'
        traefik.tags: localhost
    image: prom/prometheus:v2.9.1
    ports:
    - published: 9090
      target: 9090
    volumes:
    - /Users/Maronato/Documents/event-manager/alerts:/etc/prometheus/alerts:rw
    - /Users/Maronato/Documents/event-manager/prometheus.yml:/etc/prometheus/prometheus.yml:rw
  proxy:
    command: --docker \ --docker.swarmmode \ --docker.watch \ --docker.exposedbydefault=false
      \ --constraints=tag==localhost \ --logLevel=INFO \ --accessLog \ --web
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: Host:localhost
        traefik.port: '80'
      placement:
        constraints:
        - node.role == manager
    image: traefik:v1.7
    ports:
    - published: 80
      target: 80
    - published: 8090
      target: 8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
  redis:
    image: redis:5.0.4-alpine
    volumes:
    - app-redis-data:/data:rw
  redis-exporter:
    command:
    - --redis.addr=redis://redis:6379
    depends_on:
    - prometheus
    - redis
    image: oliver006/redis_exporter
    ports:
    - target: 9121
version: '3.7'
volumes:
  app-db-data: {}
  app-redis-data: {}
  grafana_data: {}
  portainer_data: {}
  prometheus_data: {}

