version: '3.7'
services:
  db:
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
  redis:
    volumes:
      - redis_data:/data
  prometheus:
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - ./alerts:/etc/prometheus/alerts
     - prometheus_data:/prometheus
  proxy:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
  grafana:
    volumes:
      - grafana_data:/var/lib/grafana
  portainer:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  db_data:
  redis_data:
  prometheus_data:
  grafana_data:
  portainer_data:
