version: '3.7'
services:
  proxy:
    ports:
      - '80:80'
      - '8090:8080'
  backend:
    ports:
      - '8000:8000'
  grafana:
    ports:
     - "2000:3000"
  prometheus:
    ports:
      - "9090:9090"
  portainer:
    ports:
      - "9000:9000"
