version: '3.7'
services:
  proxy:
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
  backend:
    volumes:
      - ./app/.env:/app/.env
  celeryworker:
    volumes:
      - ./app/.env:/app/.env
  celerybeat:
    volumes:
      - ./app/.env:/app/.env
