version: '3.7'
services:
  backend:
    networks:
      default:
        aliases:
          - ${DOMAIN-localhost}
      - traefik_default
  proxy:
    networks:
      - traefik_default
  grafana:
    networks:
      - traefik_default
  portainer:
    networks:
      - traefik_default

networks:
  traefik_default:
    external:
      name: traefik_default
