# Generated by Django 2.1.7 on 2019-03-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("user_profile", "0001_squashed_0010_shortcuts_is_mentor")]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=50)),
                ("text", models.TextField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="user_profile.Profile",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("warning", "Atenção"),
                            ("error", "Problema"),
                            ("success", "Sucesso"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
            ],
        )
    ]
