# Generated by Django 2.1.7 on 2019-03-13 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20180725_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='can_move',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='enroll_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900, 'Hmm, como?'), django.core.validators.MaxValueValidator(2020, 'Hmm, como?')]),
        ),
    ]
