# Generated by Django 2.1.7 on 2019-03-23 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('settings', '0001_initial'), ('settings', '0002_settings_ticket_expire'), ('settings', '0003_settings_ticket_queue_open'), ('settings', '0004_settings_verify_email'), ('settings', '0005_auto_20190320_0034'), ('settings', '0006_auto_20190320_0051')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_default_hacker', models.BooleanField(default=False)),
                ('_default_staff', models.BooleanField(default=False)),
                ('auto_admit', models.BooleanField(default=False)),
                ('max_hackers', models.IntegerField(default=100)),
                ('registration_open', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_close', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation', models.DateTimeField(default=django.utils.timezone.now)),
                ('hackathon_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('hackathon_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_expire', models.IntegerField(default=30)),
                ('ticket_queue_open', models.BooleanField(default=False)),
                ('verify_email', models.BooleanField(default=True)),
                ('require_payment', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
