# Generated by Django 2.1.7 on 2019-03-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='require_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='ticket_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
