# Generated by Django 2.1.7 on 2019-03-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20190320_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
