version: '3.7'
services:
  backend:
    build:
      context: ../app
      dockerfile: backend.dockerfile
  celeryworker:
    build:
      context: ../app
      dockerfile: worker.dockerfile
  celerybeat:
    build:
      context: ../app
      dockerfile: worker.dockerfile
  grafana:
    build:
      context: ../grafana
  prometheus:
    build:
      context: ../prometheus
