version: '3.7'
services:
  backend:
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
      - NODE_ENV=dev
      - DEBUG=True
      - APP_ENV=dev
  frontend:
    environment:
      - API_URL=http://localhost:8000
      - APP_ENV=dev
  celeryworker:
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
      - DEBUG=True
      - APP_ENV=dev
  celerybeat:
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
      - DEBUG=True
      - APP_ENV=dev
