version: '3.7'
services:
  backend:
    ports:
      - '8000:8000'
      - '7913:7913'
  backend_ws:
    ports:
      - '8001:8000'
      - '7914:7913'
  grafana:
    ports:
      - "3000:3000"
  prometheus:
    ports:
      - "9090:9090"
  portainer:
    ports:
      - "9000:9000"
