version: '3.7'
services:
  backend:
    volumes:
      - ../backend:/app
  frontend:
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
  celeryworker:
    volumes:
      - ../backend:/app
  celerybeat:
    volumes:
      - ../backend:/app

volumes:
  frontend_node_modules:
