version: '3.7'
services:
  backend:
    image: '${IMAGE_DOMAIN-localhost}/em-backend:${TAG-latest}'
  frontend:
    image: '${IMAGE_DOMAIN-localhost}/em-frontend:${TAG-latest}'
  celeryworker:
    image: '${IMAGE_DOMAIN-localhost}/em-worker:${TAG-latest}'
  celerybeat:
    image: '${IMAGE_DOMAIN-localhost}/em-worker:${TAG-latest}'
