version: '3.7'
services:
  backend:
    build:
      context: ../backend
      dockerfile: backend.dockerfile
  frontend:
    build:
      context: ../frontend
  celeryworker:
    build:
      context: ../backend
      dockerfile: worker.dockerfile
  celerybeat:
    build:
      context: ../backend
      dockerfile: worker.dockerfile
