version: '3.7'
services:
  backend:
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=dev
      - DEBUG=True
      - APP_ENV=dev
  backend_ws:
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=dev
      - DEBUG=True
      - APP_ENV=dev
  frontend:
    environment:
      - WS_URL=ws://localhost:8080
      - API_URL=http://backend:8000
      - API_URL_BROWSER=http://localhost:8000
      - APP_ENV=dev
  celeryworker:
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
      - DEBUG=True
      - APP_ENV=dev
  celerybeat:
    environment:
      - SERVER_HOST=${DOMAIN-localhost}
      - DEBUG=True
      - APP_ENV=dev
