version: '3.7'
services:
  postgres:
    env_file:
      - ../env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    env_file:
      - ../env-postgres.env
      - ../env-backend.env
      - ../env-event.env
    environment:
      - SERVER_NAME=${DOMAIN-localhost}
      - SERVER_HOST=https://${DOMAIN-localhost}
  frontend:
    env_file:
      - ../env-event.env
  celeryworker:
    env_file:
      - ../env-postgres.env
      - ../env-backend.env
    environment:
      - SERVER_HOST=https://${DOMAIN-localhost}
  celerybeat:
    env_file:
      - ../env-postgres.env
      - ../env-backend.env
    environment:
      - SERVER_HOST=https://${DOMAIN-localhost}
  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
