version: '3.7'
services:
  portainer:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  proxy:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  backend:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  frontend:
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  celeryworker:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  celerybeat:
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
