version: '3.7'
services:
  backend:
    build:
      context: ../app
      dockerfile: backend.dockerfile
      args:
        env: dev
  celeryworker:
    build:
      context: ../app
      dockerfile: worker.dockerfile
      args:
        env: dev
  celerybeat:
    build:
      context: ../app
      dockerfile: worker.dockerfile
      args:
        env: dev
  grafana:
    build:
      context: ../grafana
  prometheus:
    build:
      context: ../prometheus
