version: '3.7'
services:
  backend:
    depends_on:
      - postgres
      - redis
  frontend:
    depends_on:
      - backend
  celeryworker:
    depends_on:
      - postgres
      - redis
      - backend
  celerybeat:
    depends_on:
      - postgres
      - redis
      - backend
