version: '3.7'
services:
  backend:
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        env: dev
  backend_ws:
    build:
      context: ../backend
      dockerfile: backend.dockerfile
      args:
        env: dev
  frontend:
    build:
      context: ../frontend
      dockerfile: backend.dockerfile
      args:
        env: dev
  celeryworker:
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        env: dev
  celerybeat:
    build:
      context: ../backend
      dockerfile: worker.dockerfile
      args:
        env: dev
