version: '3.7'
services:
  backend:
    volumes:
      - ../backend:/app
  frontend:
    volumes:
      - ../frontend:/app
      - /app/node_modules
  celeryworker:
    volumes:
      - ../backend:/app
  celerybeat:
    volumes:
      - ../backend:/app
