version: '3.7'
services:
  celeryworker:
    command: celery -A project worker -l info
  celerybeat:
    command: celery -A project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  postgres:
    restart: always
  redis:
    restart: always
    command: "--maxmemory 50mb"
