# Generated by Django 2.1.7 on 2019-03-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('company', '0001_initial'), ('company', '0002_auto_20180717_1432'), ('company', '0003_auto_20180717_2237'), ('company', '0004_company_access_level'), ('company', '0005_employee_checkedin')]

    initial = True

    dependencies = [
        ('user_profile', '0006_auto_20180715_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.Company')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
                ('checkedin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scannee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_me', to='user_profile.Profile')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_scanned', to='user_profile.Profile')),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='access_level',
            field=models.IntegerField(default=0),
        ),
    ]
