# Generated by Django 2.1.7 on 2019-03-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacker', '0004_auto_20190321_0826'),
        ('pagseguro', '0003_auto_20180127_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hacker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='hacker.Hacker'),
        ),
    ]
